### ISSUE TITLE
Google has moved to Google+ Sign In

### ISSUE THREAD

**Issue by kalyan1703** [mitsuhiko/flask-openid#36]
https://developers.google.com/+/api/auth-migration#timetable

Is this something that can be handled via Flask-OpenID?

**Comment by ThiefMaster** [comment]
@puiterwijk: Any news on the OpenID Connect Flask extension?

**Comment by altryne** [comment]
@puiterwijk any news? we're 2 months away

**Comment by puiterwijk** [comment]
I think I'll have something by the end of next week.

**Comment by DavidHwu** [comment]
Just to clarify...  If I read @puiterwijk comment correctly, the Flask-OpenID support OpenID Connect for Google Plus... even though the OpenID Connect is based on Oauth2.
http://openid.net/connect/faq/

Is this an extension of this package Flask-OpenID... or will a new github be required.

**Comment by puiterwijk** [comment]
Hi,

Since OpenID Connect is an entirely different protocol, supporting both from the same codebase is not something I would like to do.
However, I have just taken over maintenance of flask-oidc, and will be moving that forward, so I would suggest looking at that: https://github.com/puiterwijk/flask-oidc.

Regards,
Patrick
