### ISSUE TITLE
openid connect?

### ISSUE THREAD

**Issue by okyere** [mitsuhiko/flask-openid#45]
Is openid connect authentication/authorisation supported? If not, are they plans to incorporate it? Thanks.

**Comment by puiterwijk** [comment]
Hi,

Since OpenID Connect is an entirely different protocol, supporting both from the same codebase is not something I would like to do.
However, I have just taken over maintenance of flask-oidc, and will be moving that forward, so I would suggest looking at that: https://github.com/puiterwijk/flask-oidc.

Regards,
Patrick

**Comment by okyere** [comment]
Good to know you've taken over that project. I'm really looking forward to a new release and making it work with any provider and not just google.
